# This workflow will 
#     > build a push/PR with Maven
#     > upload both surefire and failsafe reports in case of failure

name: Java CI with Maven in Linux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]

    name: build with Java ${{ matrix.java }} on Linux
    steps:
    - uses: actions/checkout@v5

    - name: set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    # --- START OF NEW STEPS ---
    - name: Install VNC and Openbox
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y tightvncserver openbox xfonts-base
        
    - name: Configure VNC
      run: |
        mkdir -p $HOME/.vnc
        # Copy our custom xstartup script to the VNC config directory
        cp .github/scripts/xstartup $HOME/.vnc/xstartup

    - name: Set VNC Password
      run: |
        # Create the password file required by vncserver
        mkdir -p $HOME/.vnc
        # Set a dummy password non-interactively. The password itself doesn't matter
        # as the server is restricted to localhost.
        echo 'password' | vncpasswd -f > $HOME/.vnc/passwd
        # Set the correct file permissions
        chmod 600 $HOME/.vnc/passwd
    # --- END OF NEW STEPS ---

    - name: build with Maven using VNC
      # Replace 'xvfb-run' with a call to our new script
      run: .github/scripts/execute-on-vnc.sh mvn -f pom.xml clean verify